# Generated by Django 3.0.9 on 2020-11-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='entry',
            field=models.CharField(max_length=500),
        ),
    ]
